### ISSUE TITLE
Review and update code of conduct

### ISSUE THREAD

**Issue by hugopeixoto** [alumniei/mentorados#2]
Here's a link to the old code of conduct: https://github.com/lifeonmarspt/mentorados-frontend/blob/master/app/translations/en.yml#L36

This is what commit used in 2018: https://previous.commitporto.com/2018/codeofconduct.html

I think we should go with something more like the commit version.

**Comment by hugopeixoto** [comment]
I came across another mentorship platform with a code of conduct: https://mentorcruise.com/coc/

**Comment by sofiaoreis** [comment]
**Code of Conduct**

The main goal of Mentorados is to be inclusive to the largest number of mentors and mentees, alumni and students from FEUP/LEIC degrees, with the most varied and diverse backgrounds possible. Our commitment is to provide a friendly, safe and welcoming environment for all, regardless of gender, sexual orientation, ability, ethnicity, socioeconomic status, and religion.

This code of conduct outlines what behaviors we expect the community to follow, as well as the consequences for unacceptable behavior. 

If you are a FEUP/LEIC alumni or student, we invite you to participate in this platform to help us create a safe and positive space to share experiences, knowledge and questions.

Students and mentors are expected to behave by the following precepts:

- Respect the availability and contributions of the platform mentors, who offer their support pro bono. 
- Keep your data up to date. Turn your profile as inactive when you are not available to mentor students. 
- Cultivate a network of support and encouragement for each other.
- Respect confidentiality over the elements and information shared in this platform.
- Respect the community. Do not proliferate demeaning, discriminatory, or harassing behavior and speech. 
- Report members that conduct against our code of conduct.

Members that exercise the following behaviors will be suspended from the platform for a week. Upon repeat behavior, or if the community believes you are not acting in good faith, you may be asked to leave permanently.

- Proliferate sexist, racist, homophobic, transphobic, ableist, or otherwise discriminatory jokes and language will be banned from the platform. 
- Post and/or display sexually explicit, violent, or inappropriate material.
- Disrespect in any way a member of the community.

_Reporting_
If you are subject to or witness unacceptable behavior, or have any other concerns, please notify us by writing to <e-mail>.

If you feel you have been unfairly accused of violating this Code of Conduct, you should notify <e-mail> with a concise description of your injury.

**Comment by sofiaoreis** [comment]
what do you think @hugopeixoto ? any ideas to improve the code of conduct?

**Comment by hugopeixoto** [comment]
Thanks for working on this. Two notes:

> Keep your data up to date. Turn your profile as inactive when you are not available to mentor students.

I like this, but I think we should rewrite this to emphasize that the point is to respect students that are looking for mentors.

**Suggestion**: Respect students time by keeping your profile up to date and letting us know when you are not available to mentor students.

> Members that exercise the following behaviors will be suspended from the platform for a week. Upon repeat behavior, or if the community believes you are not acting in good faith, you may be asked to leave permanently.

This makes sense for mentorcruise, where mentors charge for mentorship, but I don't think it applies to us. I prefer the language similar to the one used in commit's CoC:

> If a participant engages in harassing behavior, the conference organisers may take any action they deem appropriate, including warning the offender or expulsion from the conference.

It gives us more latitude when handling abuse, and doesn't leave room for "I can be abusive once and it will be OK".

**Suggestion**: If a participant engages in harassing behavior, the staff may take any action they deem appropriate, including warning the offender or expulsion from the platform.

**Comment by sofiaoreis** [comment]
**TO DO:**
- [ ] Translate the EN code of conduct to PT

**Comment by hugopeixoto** [comment]
Closed in favor of #11.
